apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::636999724661:user/jenkins
      username: jenkins
      groups:
        - system:masters