---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone
  labels:
    app: capstone
  namespace: default
spec:
  selector:
    matchLabels:
      app: capstone
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
      - name: capstone
        image: aanorbel/ud-nd9991-capstone:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: capstone
spec:
  selector:
    app: capstone
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000